# MySQL ConfigMap for primary and replica configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  labels:
    app: mysql
data:
  # Primary configuration
  master.cnf: |
    # Apply this config only on the primary.
    [mysqld]
    log-bin
    skip-host-cache
    skip-name-resolve
    
  # Replica configuration  
  slave.cnf: |
    # Apply this config only on replicas.
    [mysqld]
    super-read-only
    skip-host-cache
    skip-name-resolve
